name: Test Build and Run Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: telegramus-test-${{ matrix.platform }}
        platforms: linux/${{ matrix.platform }}
    - run: |
        docker run --rm "telegramus-test-${{ matrix.platform }}" /app/telegramus --version